// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagementSystem.Api.Data;

#nullable disable

namespace TaskManagementSystem.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009060255_ExtendActivityVerbsForGit")]
    partial class ExtendActivityVerbsForGit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_activities_actor_user_id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("idx_activities_project_created");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("idx_activities_task_created");

                    b.ToTable("activities", null, t =>
                        {
                            t.HasCheckConstraint("chk_activities_verb", "verb IN ('CREATED', 'UPDATED', 'MOVED', 'COMMENTED', 'GIT_BRANCH_CREATED', 'GIT_PR_OPENED', 'GIT_PR_MERGED', 'GIT_PR_CLOSED', 'GIT_COMMIT_LINKED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<long?>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("idx_audit_logs_actor_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_logs_created_at");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_audit_logs_workspace_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.CommentMention", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId", "UserId")
                        .HasName("pk_comment_mentions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_comment_mentions_user_id");

                    b.ToTable("comment_mentions", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Cycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PLANNED")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_cycles");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_cycles_project_id");

                    b.ToTable("cycles", null, t =>
                        {
                            t.HasCheckConstraint("chk_cycles_status", "status IN ('PLANNED', 'ACTIVE', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.GitConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalAccount")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("SecretRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("secret_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_git_connections");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_git_connections_workspace_id");

                    b.HasIndex("WorkspaceId", "Provider", "ExternalAccount")
                        .IsUnique()
                        .HasDatabaseName("uq_git_connections_workspace_provider_account");

                    b.ToTable("git_connections", null, t =>
                        {
                            t.HasCheckConstraint("chk_git_connections_auth_type", "auth_type IN ('GITHUB_APP', 'OAUTH', 'PAT', 'GROUP_TOKEN')");

                            t.HasCheckConstraint("chk_git_connections_provider", "provider IN ('GITHUB', 'GITLAB')");

                            t.HasCheckConstraint("chk_git_connections_status", "status IN ('ACTIVE', 'DISABLED', 'ERROR')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.GitIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_user_id");

                    b.Property<string>("ExternalUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_username");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_git_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_git_identities_user_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_git_identities_workspace_id");

                    b.HasIndex("WorkspaceId", "Provider", "ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_git_identities_workspace_provider_user");

                    b.ToTable("git_identities", null, t =>
                        {
                            t.HasCheckConstraint("chk_git_identities_provider", "provider IN ('GITHUB', 'GITLAB')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Invitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("InvitedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("invited_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("MEMBER")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_invitations_invited_by");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("invitations_token_hash_key");

                    b.HasIndex("WorkspaceId", "Email")
                        .HasDatabaseName("idx_invitations_workspace_email");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("chk_invitations_role", "role IN ('ADMIN', 'MEMBER', 'VIEWER')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_labels_workspace_id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_labels_workspace_name");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Milestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_milestones_project_id");

                    b.ToTable("milestones", null, t =>
                        {
                            t.HasCheckConstraint("chk_milestones_status", "status IN ('OPEN', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("read_at");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_notifications_actor_user_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_notifications_task_id");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("idx_notifications_recipient");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("chk_notifications_type", "type IN ('MENTION', 'ASSIGNED', 'STATUS_CHANGED', 'COMMENT', 'DUE_SOON', 'DUE_OVERDUE')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_projects_workspace_id");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("chk_projects_status", "status IN ('ACTIVE', 'COMPLETED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.ProjectMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("MEMBER")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_project_members_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_project_members_user_id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_members_project_user");

                    b.ToTable("project_members", null, t =>
                        {
                            t.HasCheckConstraint("chk_project_members_role", "role IN ('OWNER', 'MEMBER')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("refresh_tokens_token_hash_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_refresh_tokens_revoked_reason", "revoked_reason IS NULL OR revoked_reason IN ('ROTATED', 'LOGOUT', 'REUSE_DETECTED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.RepositoryLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_branch");

                    b.Property<string>("ExternalRepoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_repo_id");

                    b.Property<long>("GitConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_connection_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("repo_full_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_repository_links");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_repository_links_project_id");

                    b.HasIndex("GitConnectionId", "ExternalRepoId")
                        .IsUnique()
                        .HasDatabaseName("uq_repository_links_connection_repo");

                    b.ToTable("repository_links", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.SavedView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("view_type");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_views");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("idx_saved_views_owner_user_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_saved_views_workspace_id");

                    b.ToTable("saved_views", null, t =>
                        {
                            t.HasCheckConstraint("chk_saved_views_view_type", "view_type IN ('LIST', 'BOARD')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskChecklistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_done");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_task_checklist_items");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_task_checklist_items_task_id");

                    b.ToTable("task_checklist_items", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Edited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("edited");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_task_comments_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_task_comments_user_id");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BlockedTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_task_id");

                    b.Property<long>("BlockingTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocking_task_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_task_dependencies");

                    b.HasIndex("BlockedTaskId")
                        .HasDatabaseName("idx_task_dependencies_blocked_task_id");

                    b.HasIndex("BlockingTaskId")
                        .HasDatabaseName("idx_task_dependencies_blocking_task_id");

                    b.HasIndex("BlockingTaskId", "BlockedTaskId")
                        .IsUnique()
                        .HasDatabaseName("uq_task_dependencies_pair");

                    b.ToTable("task_dependencies", null, t =>
                        {
                            t.HasCheckConstraint("chk_task_dependencies_no_self", "blocking_task_id <> blocked_task_id");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskGitLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalRef")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_ref");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("link_type");

                    b.Property<long>("RepositoryLinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_link_id");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_task_git_links");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_task_git_links_task_id");

                    b.HasIndex("RepositoryLinkId", "LinkType", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("uq_task_git_links_repo_type_ref");

                    b.ToTable("task_git_links", null, t =>
                        {
                            t.HasCheckConstraint("chk_task_git_links_state", "state IS NULL OR state IN ('OPEN', 'MERGED', 'CLOSED')");

                            t.HasCheckConstraint("chk_task_git_links_type", "link_type IN ('BRANCH', 'PR', 'MR', 'COMMIT')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssigneeId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignee_id");

                    b.Property<double>("BoardPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("board_position");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int?>("EstimatePoints")
                        .HasColumnType("integer")
                        .HasColumnName("estimate_points");

                    b.Property<long?>("MilestoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("milestone_id");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("MEDIUM")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("TODO")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("idx_tasks_assignee_id");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("idx_tasks_cycle_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("idx_tasks_due_date");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("idx_tasks_milestone_id");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("idx_tasks_parent_task_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_tasks_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tasks_status");

                    b.HasIndex("ProjectId", "Status", "BoardPosition")
                        .HasDatabaseName("idx_tasks_board_order");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("chk_tasks_priority", "priority IN ('LOW', 'MEDIUM', 'HIGH')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskLabel", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("LabelId")
                        .HasColumnType("bigint")
                        .HasColumnName("label_id");

                    b.HasKey("TaskId", "LabelId")
                        .HasName("pk_task_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("idx_task_labels_label_id");

                    b.ToTable("task_labels", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_task_status_histories");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_task_status_histories_changed_by");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_task_status_histories_task_id");

                    b.ToTable("task_status_histories", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskWatcher", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TaskId", "UserId")
                        .HasName("pk_task_watchers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_task_watchers_user_id");

                    b.ToTable("task_watchers", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TransitionRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("ToStatusKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status_key");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_transition_rules");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_transition_rules_project_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_transition_rules_workspace_id");

                    b.ToTable("transition_rules", null, t =>
                        {
                            t.HasCheckConstraint("chk_transition_rules_trigger", "trigger IN ('BRANCH_CREATED', 'PR_OPENED', 'MR_OPENED', 'PR_MERGED', 'MR_MERGED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_event_id");

                    b.Property<long>("GitConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_connection_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("SignatureVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_verified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("RECEIVED")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_webhook_events_received_at");

                    b.HasIndex("GitConnectionId", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_webhook_events_connection_event");

                    b.ToTable("webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("chk_webhook_events_status", "status IN ('RECEIVED', 'PROCESSED', 'SKIPPED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WorkflowState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_states");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_workflow_states_workspace_id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_workflow_states_workspace_key");

                    b.ToTable("workflow_states", null, t =>
                        {
                            t.HasCheckConstraint("chk_workflow_states_category", "category IN ('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WorkspaceMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("MEMBER")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_workspace_members_user_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("idx_workspace_members_workspace_id");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_workspace_members_workspace_user");

                    b.ToTable("workspace_members", null, t =>
                        {
                            t.HasCheckConstraint("chk_workspace_members_role", "role IN ('ADMIN', 'MEMBER', 'VIEWER')");
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Activity", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_actor_user");

                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_project");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_activities_task");

                    b.Navigation("ActorUser");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.AuditLog", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_actor_user");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.CommentMention", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.TaskComment", "Comment")
                        .WithMany("CommentMentions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_mentions_comment");

                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_mentions_user");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Cycle", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycles_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.GitConnection", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_connections_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.GitIdentity", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_identities_user");

                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_identities_workspace");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Invitation", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_invited_by");

                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany("Invitations")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_workspace");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Label", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany("Labels")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labels_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Milestone", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Notification", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_actor_user");

                    b.HasOne("TaskManagementSystem.Api.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_recipient_user");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_task");

                    b.Navigation("ActorUser");

                    b.Navigation("RecipientUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Project", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.ProjectMember", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_project");

                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_user");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.RepositoryLink", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.GitConnection", "GitConnection")
                        .WithMany()
                        .HasForeignKey("GitConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repository_links_connection");

                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repository_links_project");

                    b.Navigation("GitConnection");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.SavedView", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_views_owner_user");

                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_views_workspace");

                    b.Navigation("OwnerUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskChecklistItem", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_checklist_items_task");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskComment", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_task");

                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany("TaskComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_user");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskDependency", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "BlockedTask")
                        .WithMany()
                        .HasForeignKey("BlockedTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_blocked_task");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "BlockingTask")
                        .WithMany()
                        .HasForeignKey("BlockingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_blocking_task");

                    b.Navigation("BlockedTask");

                    b.Navigation("BlockingTask");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskGitLink", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.RepositoryLink", "RepositoryLink")
                        .WithMany()
                        .HasForeignKey("RepositoryLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_git_links_repository_link");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_git_links_task");

                    b.Navigation("RepositoryLink");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_assignee");

                    b.HasOne("TaskManagementSystem.Api.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_cycle");

                    b.HasOne("TaskManagementSystem.Api.Models.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_milestone");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tasks_parent_task");

                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_project");

                    b.Navigation("Assignee");

                    b.Navigation("Cycle");

                    b.Navigation("Milestone");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskLabel", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Label", "Label")
                        .WithMany("TaskLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_label");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany("TaskLabels")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_task");

                    b.Navigation("Label");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskStatusHistory", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "ChangedByUser")
                        .WithMany("TaskStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_status_histories_user");

                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany("StatusHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_status_histories_task");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskWatcher", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_watchers_task");

                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_watchers_user");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TransitionRule", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transition_rules_project");

                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transition_rules_workspace");

                    b.Navigation("Project");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WebhookEvent", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.GitConnection", "GitConnection")
                        .WithMany()
                        .HasForeignKey("GitConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_events_connection");

                    b.Navigation("GitConnection");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WorkflowState", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany("WorkflowStates")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_states_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.WorkspaceMember", b =>
                {
                    b.HasOne("TaskManagementSystem.Api.Models.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_user");

                    b.HasOne("TaskManagementSystem.Api.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspace");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Label", b =>
                {
                    b.Navigation("TaskLabels");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskComment", b =>
                {
                    b.Navigation("CommentMentions");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.TaskItem", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Comments");

                    b.Navigation("StatusHistories");

                    b.Navigation("Subtasks");

                    b.Navigation("TaskLabels");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("ProjectMembers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TaskComments");

                    b.Navigation("TaskStatusHistories");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("TaskManagementSystem.Api.Models.Workspace", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Labels");

                    b.Navigation("Members");

                    b.Navigation("Projects");

                    b.Navigation("WorkflowStates");
                });
#pragma warning restore 612, 618
        }
    }
}
